"""Pi-side HX1 protocol and Servo 2040 client core."""

from .client import (
    HX1ClientCore,
    HX1ClientError,
    HX1PeerInfo,
    HX1PeerMismatchError,
    HX1SessionError,
    HX1UnexpectedResponseError,
)
from .config import (
    HX1ClientConfig,
    HX1ConfigError,
    load_hx1_client_config,
    parse_hx1_client_config,
)
from .link import (
    HX1Link,
    HX1LinkError,
)
from .messages import (
    HX1Ack,
    HX1Event,
    HX1Info,
    HX1Inbound,
    HX1MessageError,
    HX1Nack,
    HX1Outbound,
    HX1Status,
    HX1UnknownMessage,
    ZERO_SESSION,
    degrees_to_centidegrees,
    joint_degrees_to_centidegrees,
    parse_inbound,
)
from .protocol import (
    HX1CRCError,
    HX1Frame,
    HX1FrameFormatError,
    HX1FrameTooLongError,
    HX1LineFramer,
    HX1ProtocolError,
    HX1Sequence,
    MAX_FRAME_BYTES,
    PROTOCOL_MAJOR,
    PROTOCOL_MINOR,
    UINT32_MAX,
    crc16_ccitt_false,
    encode_frame,
    parse_frame,
    sequence_is_newer,
)
from .serial_transport import (
    HX1SerialDependencyError,
    SerialHX1Transport,
    create_serial_hx1_transport,
)
from .transport import (
    FakeHX1Transport,
    HX1Transport,
    HX1TransportClosedError,
    HX1TransportError,
    HX1TransportValueError,
)

__all__ = [
    "FakeHX1Transport",
    "HX1Ack",
    "HX1CRCError",
    "HX1ClientConfig",
    "HX1ClientCore",
    "HX1ClientError",
    "HX1ConfigError",
    "HX1Event",
    "HX1Frame",
    "HX1FrameFormatError",
    "HX1FrameTooLongError",
    "HX1Info",
    "HX1Inbound",
    "HX1LineFramer",
    "HX1Link",
    "HX1LinkError",
    "HX1MessageError",
    "HX1Nack",
    "HX1Outbound",
    "HX1PeerInfo",
    "HX1PeerMismatchError",
    "HX1ProtocolError",
    "HX1Sequence",
    "HX1SerialDependencyError",
    "HX1SessionError",
    "HX1Status",
    "HX1Transport",
    "HX1TransportClosedError",
    "HX1TransportError",
    "HX1TransportValueError",
    "HX1UnexpectedResponseError",
    "HX1UnknownMessage",
    "MAX_FRAME_BYTES",
    "PROTOCOL_MAJOR",
    "PROTOCOL_MINOR",
    "SerialHX1Transport",
    "UINT32_MAX",
    "ZERO_SESSION",
    "crc16_ccitt_false",
    "create_serial_hx1_transport",
    "degrees_to_centidegrees",
    "encode_frame",
    "joint_degrees_to_centidegrees",
    "load_hx1_client_config",
    "parse_frame",
    "parse_hx1_client_config",
    "parse_inbound",
    "sequence_is_newer",
]
