#!/usr/bin/env python3
"""Software-only joint-rate qualification baseline.

This tool evaluates canonical logical joint velocities generated by a reference
tripod gait over an explicit command envelope. It never opens hardware devices.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path

from model import (
    JOINT_ORDER,
    LEG_ORDER,
    LinkLengths,
    compute_logical_frame,
    joint_names,
    neutral_foot_body,
)
from smoothing import OnePoleSlewUD
from tripod import GaitParams, TripodGait

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]
DEFAULT_CONFIG = HERE / "scenarios.json"
DEFAULT_OUTPUT = REPO_ROOT / "build/qualification/joint-rates"


def percentile(values: list[float], pct: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    rank = (pct / 100.0) * (len(ordered) - 1)
    lo = int(math.floor(rank))
    hi = int(math.ceil(rank))
    if lo == hi:
        return ordered[lo]
    weight = rank - lo
    return ordered[lo] * (1.0 - weight) + ordered[hi] * weight


def round_up(value: float, quantum: int) -> int:
    if quantum <= 0:
        raise ValueError("rounding quantum must be positive")
    return int(math.ceil(value / quantum) * quantum)


def command_for_time(
    scenario: dict,
    elapsed: float,
    duration: float,
) -> tuple[float, float, float]:
    fraction = 0.0
    t_fraction = min(max(elapsed / max(duration, 1e-9), 0.0), 1.0)

    for segment in scenario["segments"]:
        next_fraction = fraction + float(segment["fraction"])
        if t_fraction <= next_fraction + 1e-12:
            return (
                float(segment["vx"]),
                float(segment["vy"]),
                float(segment["yaw"]),
            )
        fraction = next_fraction

    last = scenario["segments"][-1]
    return float(last["vx"]), float(last["vy"]), float(last["yaw"])


def validate_config(cfg: dict) -> None:
    hz = float(cfg["control_hz"])
    duration = float(cfg["scenario_duration_s"])
    if hz <= 0.0:
        raise ValueError("control_hz must be > 0")
    if duration <= 0.0:
        raise ValueError("scenario_duration_s must be > 0")

    if len(cfg.get("scenarios", [])) == 0:
        raise ValueError("at least one scenario is required")

    for scenario in cfg["scenarios"]:
        segments = scenario.get("segments", [])
        if not segments:
            raise ValueError(f"{scenario.get('name')}: no segments")
        total = sum(float(segment["fraction"]) for segment in segments)
        if abs(total - 1.0) > 1e-9:
            raise ValueError(
                f"{scenario.get('name')}: segment fractions sum to {total}, expected 1.0"
            )


def run_scenario(
    scenario: dict,
    *,
    control_hz: float,
    duration_s: float,
    lengths: LinkLengths,
    gait_params: GaitParams,
    neutral: dict[str, tuple[float, float, float]],
    smoothing_cfg: dict,
) -> list[dict]:
    dt = 1.0 / control_hz
    steps = max(2, int(round(duration_s * control_hz)))
    gait = TripodGait()
    gait.reset()

    samples: list[dict] = []
    previous: list[float] | None = None

    f_vx = OnePoleSlewUD(
        0.0,
        float(smoothing_cfg["tau_v_s"]),
        float(smoothing_cfg["accel_v_mm_s2"]),
        float(smoothing_cfg["decel_v_mm_s2"]),
    )
    f_vy = OnePoleSlewUD(
        0.0,
        float(smoothing_cfg["tau_v_s"]),
        float(smoothing_cfg["accel_v_mm_s2"]),
        float(smoothing_cfg["decel_v_mm_s2"]),
    )
    f_yaw = OnePoleSlewUD(
        0.0,
        float(smoothing_cfg["tau_yaw_s"]),
        float(smoothing_cfg["accel_yaw_deg_s2"]),
        float(smoothing_cfg["decel_yaw_deg_s2"]),
    )

    for tick in range(steps):
        t = tick * dt
        raw_vx, raw_vy, raw_yaw = command_for_time(scenario, t, duration_s)
        vx = f_vx.update(raw_vx, dt)
        vy = f_vy.update(raw_vy, dt)
        yaw = f_yaw.update(raw_yaw, dt)

        targets = {
            leg: gait.foot_body_target(
                t=t,
                leg=leg,
                vx=vx,
                vy=vy,
                yaw_rate_deg_s=yaw,
                neutral_foot_body=neutral,
                params=gait_params,
            )
            for leg in LEG_ORDER
        }
        frame = compute_logical_frame(targets, lengths)

        if previous is not None:
            for index, (prev, current) in enumerate(zip(previous, frame)):
                delta = current - prev
                rate_deg_s = abs(delta) / dt
                samples.append(
                    {
                        "scenario": scenario["name"],
                        "tick": tick,
                        "time_s": t,
                        "index": index,
                        "joint": joint_names()[index],
                        "angle_deg": current,
                        "delta_deg": delta,
                        "rate_deg_s": rate_deg_s,
                        "rate_cd_s": rate_deg_s * 100.0,
                        "vx_mm_s": vx,
                        "vy_mm_s": vy,
                        "yaw_deg_s": yaw,
                        "raw_vx_mm_s": raw_vx,
                        "raw_vy_mm_s": raw_vy,
                        "raw_yaw_deg_s": raw_yaw,
                    }
                )

        previous = frame

    return samples


def summarize(samples: list[dict], cfg: dict) -> dict:
    names = joint_names()
    headroom = float(cfg["candidate_headroom_multiplier"])
    rounding = int(cfg["candidate_rounding_cd_s"])

    by_joint: dict[str, dict] = {}
    for index, name in enumerate(names):
        rates = [
            float(row["rate_cd_s"]) for row in samples if int(row["index"]) == index
        ]
        peak = max(rates, default=0.0)
        peak_row = max(
            (row for row in samples if int(row["index"]) == index),
            key=lambda row: float(row["rate_cd_s"]),
            default=None,
        )
        by_joint[name] = {
            "index": index,
            "peak_cd_s": round(peak, 3),
            "peak_deg_s": round(peak / 100.0, 3),
            "p99_cd_s": round(percentile(rates, 99.0), 3),
            "p99_9_cd_s": round(percentile(rates, 99.9), 3),
            "candidate_cd_s": round_up(peak * headroom, rounding) if peak > 0 else 0,
            "peak_scenario": peak_row["scenario"] if peak_row else None,
            "peak_time_s": round(float(peak_row["time_s"]), 6) if peak_row else None,
        }

    by_family: dict[str, dict] = {}
    for family in JOINT_ORDER:
        family_names = [name for name in names if name.endswith("_" + family)]
        rates = [
            float(row["rate_cd_s"])
            for row in samples
            if str(row["joint"]) in family_names
        ]
        peak = max(rates, default=0.0)
        by_family[family] = {
            "peak_cd_s": round(peak, 3),
            "peak_deg_s": round(peak / 100.0, 3),
            "p99_cd_s": round(percentile(rates, 99.0), 3),
            "p99_9_cd_s": round(percentile(rates, 99.9), 3),
            "candidate_cd_s": round_up(peak * headroom, rounding) if peak > 0 else 0,
        }

    overall_peak = max((float(row["rate_cd_s"]) for row in samples), default=0.0)
    overall_row = max(samples, key=lambda row: float(row["rate_cd_s"]), default=None)

    return {
        "qualification_version": int(cfg["qualification_version"]),
        "basis": "software_only_v4_reference_motion_envelope",
        "qualified_for_firmware_profile": False,
        "control_hz": float(cfg["control_hz"]),
        "sample_interval_ms": 1000.0 / float(cfg["control_hz"]),
        "scenario_count": len(cfg["scenarios"]),
        "sample_count": len(samples),
        "candidate_headroom_multiplier": headroom,
        "candidate_rounding_cd_s": rounding,
        "overall": {
            "peak_cd_s": round(overall_peak, 3),
            "peak_deg_s": round(overall_peak / 100.0, 3),
            "peak_joint": overall_row["joint"] if overall_row else None,
            "peak_scenario": overall_row["scenario"] if overall_row else None,
            "peak_time_s": round(float(overall_row["time_s"]), 6)
            if overall_row
            else None,
        },
        "by_family": by_family,
        "by_joint": by_joint,
        "notes": [
            "These values are an initial software baseline, not final actuator safety qualification.",
            "Do not promote these candidates into the actuator profile based on this software-only tool alone; separate physical qualification is required.",
            "Revision 3 currently uses 25000 cd/s based on separately documented physical qualification.",
            "Re-run this tool whenever command limits, gait timing, step height, stance height, geometry, or trajectory generation changes.",
        ],
    }


def write_csv(path: Path, samples: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "scenario",
        "tick",
        "time_s",
        "index",
        "joint",
        "angle_deg",
        "delta_deg",
        "rate_deg_s",
        "rate_cd_s",
        "vx_mm_s",
        "vy_mm_s",
        "yaw_deg_s",
        "raw_vx_mm_s",
        "raw_vy_mm_s",
        "raw_yaw_deg_s",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(samples)


def print_summary(summary: dict) -> None:
    print()
    print("Joint-rate qualification baseline")
    print("=" * 72)
    print(
        f"Scenarios: {summary['scenario_count']} | "
        f"Control: {summary['control_hz']:.1f} Hz | "
        f"Samples: {summary['sample_count']}"
    )
    print()
    print(
        f"{'Family':<10} {'Peak deg/s':>12} {'P99 deg/s':>12} {'P99.9 deg/s':>14} {'Candidate cd/s':>16}"
    )
    print("-" * 72)
    for family, data in summary["by_family"].items():
        print(
            f"{family:<10} "
            f"{data['peak_deg_s']:>12.2f} "
            f"{data['p99_cd_s'] / 100.0:>12.2f} "
            f"{data['p99_9_cd_s'] / 100.0:>14.2f} "
            f"{data['candidate_cd_s']:>16d}"
        )

    print()
    overall = summary["overall"]
    print(
        "Overall peak: "
        f"{overall['peak_deg_s']:.2f} deg/s "
        f"({overall['peak_cd_s']:.0f} cd/s), "
        f"joint={overall['peak_joint']}, "
        f"scenario={overall['peak_scenario']}, "
        f"t={overall['peak_time_s']}s"
    )
    print()
    print("IMPORTANT: candidates are software-envelope values only.")
    print("Do not treat them as qualified actuator hard limits without separate")
    print("physical qualification and documented evidence.")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    cfg = json.loads(args.config.read_text(encoding="utf-8"))
    validate_config(cfg)

    geometry = cfg["geometry"]
    lengths = LinkLengths(
        coxa=float(geometry["coxa_mm"]),
        femur=float(geometry["femur_mm"]),
        tibia=float(geometry["tibia_mm"]),
    )

    gait_cfg = cfg["gait"]
    gait_params = GaitParams(
        cycle_hz=float(gait_cfg["cycle_hz"]),
        step_height=float(gait_cfg["step_height_mm"]),
        stance_z=float(gait_cfg["stance_z_mm"]),
        duty=float(gait_cfg["duty"]),
        max_step=float(gait_cfg["max_step_mm"]),
        start_blend_s=float(gait_cfg["start_blend_s"]),
    )

    neutral = neutral_foot_body()
    samples: list[dict] = []
    for scenario in cfg["scenarios"]:
        samples.extend(
            run_scenario(
                scenario,
                control_hz=float(cfg["control_hz"]),
                duration_s=float(cfg["scenario_duration_s"]),
                lengths=lengths,
                gait_params=gait_params,
                neutral=neutral,
                smoothing_cfg=cfg["command_smoothing"],
            )
        )

    summary = summarize(samples, cfg)

    args.output.mkdir(parents=True, exist_ok=True)
    write_csv(args.output / "samples.csv", samples)
    (args.output / "summary.json").write_text(
        json.dumps(summary, indent=2) + "\n",
        encoding="utf-8",
    )

    print_summary(summary)
    print()
    print(f"Wrote {args.output / 'summary.json'}")
    print(f"Wrote {args.output / 'samples.csv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
